### ISSUE TITLE
label -1 in Penn94

### ISSUE THREAD

**Issue by HaitaoMao** [CUAI/Non-Homophily-Large-Scale#12]
Hi I found there are nodes with label -1 in the penn dataset, and none of them are included in the train/validation/test set. But how can I handle those nodes when calculate the homophily ratio? Thanks

**Comment by decoherencer** [comment]
Those nodes are unlabelled, so you ignore those nodes and edges connected to those nodes in h ratio too  https://github.com/CUAI/Non-Homophily-Large-Scale/blob/260eaf44e4d90430f71abb3510abb8fa400bd4a0/dataset.py#L142

**Comment by cptq** [comment]
Indeed negative labels are ignored, see e.g.: **https://github.com/CUAI/Non-Homophily-Large-Scale/blob/260eaf44e4d90430f71abb3510abb8fa400bd4a0/homophily.py#L76**

**Comment by HaitaoMao** [comment]
Thanks. Does this mean that those nodes are ignored in the calculation of homophily ratio but those nodes can still be utilized for aggregation in the training process.

**Comment by cptq** [comment]
Yes, this is correct!
