### ISSUE TITLE
Can NOT download twitch-gamer dataset

### ISSUE THREAD

**Issue by Kwongfei** [CUAI/Non-Homophily-Large-Scale#15]
I can not download the twitch-gamer dataset:

urllib3.exceptions.SSLError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

requests.exceptions.ProxyError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1fA9VIIEI8N0L27MSQfcBzJgRQLvSbrvR (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))))

I also tried to download through the webpage: https://drive.google.com/file/d/1XLETC6dG3lVl7kDmytEJ52hvDMVdxnZ0/view, but it doesn't work.

**Comment by cptq** [comment]
Did you try to download from the original source? https://github.com/benedekrozemberczki/datasets

**Comment by Kwongfei** [comment]
Thanks a lot!

**Comment by Kwongfei** [comment]
> Did you try to download from the original source? https://github.com/benedekrozemberczki/datasets

Thanks a lot!
