### ISSUE TITLE
Datasets clarification

### ISSUE THREAD

**Issue by devnkong** [CUAI/Non-Homophily-Large-Scale#3]
Hey authors,

Thanks for the great work!

I saw you people have another repo for a WWW  paper. Are the datasets identical? Which repo shall I use?

Also I haven't dived deeply into the specs of the datasets, could you inform me how are the input node features of the datasets are constructed?

Thank you!

**Comment by cptq** [comment]
Hi!

Yes, we do have another repo for the WWW paper. There is some overlap in datasets (Penn94, pokec, arXiv-year, snap-patents), though there are datasets in the WWW not in this one, and vice versa. I would recommend using the datasets in this NeurIPS paper, though if your method is inefficient the datasets in the other paper can be used, as they are smaller.

Appendix D.2 contains specific information on the node features. arXiv-year and wiki have word embeddings for node features, while the other datasets have assorted numerical data (e.g. public user information like age and region for social networks).

**Comment by devnkong** [comment]
That is clear, thanks!
