### ISSUE TITLE
twitch-gamer_edges.csv empty file

### ISSUE THREAD

**Issue by devnkong** [CUAI/Non-Homophily-Large-Scale#4]
Hi authors,

The twitch-gamer_edges.csv file downloaded for me turned out to be an empty file. Would you please check that? Thanks.

**Comment by Xiuyu-Li** [comment]
Hi Kezhi,

It seems like the `gdd` connection to our google drive is a bit unstable (especially after requesting multiple times at once). Can you delete your downloaded `data/twitch-gamer_edges.csv` and retry the data loading command to download again once you unsucessfully download an empty file for now? We may consider hosting our datasets on somewhere more robust in the future.

**Comment by devnkong** [comment]
Hi Xiuyu,

Thanks for the prompt reply! I tried to redownload it and it worked. Thanks.
