### ISSUE TITLE
pokec cannot be downloaded directly, either

### ISSUE THREAD

**Issue by devnkong** [CUAI/Non-Homophily-Large-Scale#5]
Hi authors,

Again I found pokec cannot be downloaded using your gdd script. The file I downloaded is an html file, from that I can download anyway, but just let you guys know.

The html file:

```
<!DOCTYPE html><html><head><title>Google Drive - Download warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="uH/xyEi4EXe5R83mihluqg">/* Copyright 2022 Google Inc. All Rights Reserved. */
.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}</style><link rel="icon" href="null"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive has detected issues with your download</p><p class="uc-warning-subcaption">This file is too large for Google to scan for viruses.</p><p class="uc-warning-subcaption">This file is executable and may harm your computer.</p><p class="uc-warning-subcaption"><span class="uc-name-size"><a href="/open?id=1dNs5E7BrWJbgcHeQ_zuy5Ozp2tRCWG0y">pokec.mat</a> (1.3G)</span></p><form id="downloadForm" action="https://docs.google.com/uc?export=download&amp;id=1dNs5E7BrWJbgcHeQ_zuy5Ozp2tRCWG0y&amp;confirm=t" method="post"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
```

**Comment by devnkong** [comment]
Also I found another issue. Pokec is said to be a binary classification task but I found actually there classes in total. 163 nodes were labeled -1 as below.

```
(Pdb) y.unique()
tensor([-1,  0,  1])
(Pdb) (y==-1).sum()
tensor(163)
```

Would you also check that? Thanks.

**Comment by Xiuyu-Li** [comment]
Hi Kezhi,

A label being negative in pokec indicates it is missing in the raw data. Those labels will not be used in training and evaluation as `ignore_negative` was set to `True` by default. See https://github.com/CUAI/Non-Homophily-Large-Scale/blob/260eaf44e4d90430f71abb3510abb8fa400bd4a0/dataset.py#L61



> Also I found another issue. Pokec is said to be a binary classification task but I found actually there classes in total. 163 nodes were labeled -1 as below.
> 
> ```
> (Pdb) y.unique()
> tensor([-1,  0,  1])
> (Pdb) (y==-1).sum()
> tensor(163)
> ```
> 
> Would you also check that? Thanks.

**Comment by Xiuyu-Li** [comment]
Thanks for informing us about this! Will take a look

> Hi authors,
> 
> Again I found pokec cannot be downloaded using your gdd script. The file I downloaded is an html file, from that I can download anyway, but just let you guys know.
> 
> The html file:
> 
> ```
> <!DOCTYPE html><html><head><title>Google Drive - Download warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="uH/xyEi4EXe5R83mihluqg">/* Copyright 2022 Google Inc. All Rights Reserved. */
> .goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}.goog-link-button{position:relative;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.grecaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-size a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.uc-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}</style><link rel="icon" href="null"/></head><body><div class="uc-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive has detected issues with your download</p><p class="uc-warning-subcaption">This file is too large for Google to scan for viruses.</p><p class="uc-warning-subcaption">This file is executable and may harm your computer.</p><p class="uc-warning-subcaption"><span class="uc-name-size"><a href="/open?id=1dNs5E7BrWJbgcHeQ_zuy5Ozp2tRCWG0y">pokec.mat</a> (1.3G)</span></p><form id="downloadForm" action="https://docs.google.com/uc?export=download&amp;id=1dNs5E7BrWJbgcHeQ_zuy5Ozp2tRCWG0y&amp;confirm=t" method="post"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/></form></div></div><div class="uc-footer"><hr class="uc-footer-divider"></div></body></html>
> ```

**Comment by devnkong** [comment]
Hi Xiuyu, that makes sense, thanks a bunch!
